// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpPSqEAzemOEbQTQmWDMkQDaXak2Smdk8',
    appId: '1:307657066428:web:2e444d816bf7e907d48db9',
    messagingSenderId: '307657066428',
    projectId: 'sunecommerce-1355b',
    authDomain: 'sunecommerce-1355b.firebaseapp.com',
    storageBucket: 'sunecommerce-1355b.firebasestorage.app',
    measurementId: 'G-CH5CRMMFVJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWHEDhmEfa23s9lCizTMz8bXN5mJ3-Io0',
    appId: '1:307657066428:android:631ad7e4a3e2936bd48db9',
    messagingSenderId: '307657066428',
    projectId: 'sunecommerce-1355b',
    storageBucket: 'sunecommerce-1355b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2IAQOtAFdd58xw0atnrNs7UQmSeKH9_Q',
    appId: '1:307657066428:ios:95c5340729f9579fd48db9',
    messagingSenderId: '307657066428',
    projectId: 'sunecommerce-1355b',
    storageBucket: 'sunecommerce-1355b.firebasestorage.app',
    iosBundleId: 'com.example.suryaEcommerce',
  );
}
