// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnP4fvtQTDnjo0RsKOr54yiOJv0VFsPiQ',
    appId: '1:600497347289:web:9ac8d7dfbd0d0c6d867cc8',
    messagingSenderId: '600497347289',
    projectId: 'sunassociates-e01eb',
    authDomain: 'sunassociates-e01eb.firebaseapp.com',
    storageBucket: 'sunassociates-e01eb.firebasestorage.app',
    measurementId: 'G-4TB8NV236Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCj8lPyVO2PxHQ03mhjIz8feLhSclhe-wk',
    appId: '1:600497347289:android:f770abe20fca402f867cc8',
    messagingSenderId: '600497347289',
    projectId: 'sunassociates-e01eb',
    storageBucket: 'sunassociates-e01eb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvJx1Ai99nwglCMIVpEM_zaXwIktcwtvo',
    appId: '1:600497347289:ios:28048024fa69e1bd867cc8',
    messagingSenderId: '600497347289',
    projectId: 'sunassociates-e01eb',
    storageBucket: 'sunassociates-e01eb.firebasestorage.app',
    iosBundleId: 'com.example.suryaEcommerce',
  );
}
